import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useQuery } from '../hooks/useRequest';
import { catalogoRequest, inscripcionesRequest, requireList } from '../services/api';
import { categoryStyle } from '../services/presentation';
import EventCard from '../components/EventCard';
import Icon from '../components/Icon';
import { EmptyState, ErrorMessage, LoadingSpinner } from '../components/Feedback';
import { RegistrationStatus } from './RegistrationsPage';

function DashboardPanels({ events }) {
  const { session, authenticated } = useAuth();
  const registrations = useQuery(signal => inscripcionesRequest({ action: 'LIST' }, { token: session.session_token, signal }).then(data => requireList(data, 'inscripciones')), session?.session_token, authenticated);
  return <section className="dashboard-panels" aria-label="Tu experiencia EventPass"><article className="panel registrations-preview"><div className="section-heading"><h2><Icon name="ticket" />Mis inscripciones</h2><Link className="subtle-link" to="/inscripciones">Ver todas <Icon name="arrow" size={15} /></Link></div><p className="muted">Tu próxima aventura, siempre a mano.</p>{!authenticated ? <EmptyState title="Aquí empieza tu próxima historia" action={<Link to="/login" className="button secondary small">Iniciar sesión <Icon name="arrow" size={16} /></Link>}>Inicia sesión para consultar y gestionar tus inscripciones.</EmptyState> : registrations.loading ? <LoadingSpinner /> : registrations.error ? <ErrorMessage error={registrations.error} onRetry={registrations.reload} /> : !registrations.data?.length ? <EmptyState title="Tu pase está esperando">Explora los eventos y encuentra tu siguiente experiencia.</EmptyState> : <div className="registration-mini-list">{registrations.data.slice(0, 3).map(item => <Link to="/inscripciones" key={item.inscripcion_id} className="registration-mini"><Icon name="ticket" /><div><strong>{events.find(event => event.evento_id === item.evento_id)?.nombre || item.evento_id}</strong><span>{item.nombre_acreditacion}</span></div><RegistrationStatus state={item.estado} /></Link>)}</div>}</article><article className="panel assistant-preview"><div className="assistant-orbit" aria-hidden="true"><Icon name="bot" size={75} /></div><span className="eyebrow cyan-text">TU COPILOTO GEEK</span><h2>Event<span className="gradient-text">Pass</span> Assistant</h2><p>Menos dudas.<br />Más experiencias increíbles.</p><ul className="check-list"><li><Icon name="check" />Descubre eventos y actividades</li><li><Icon name="check" />Consulta fechas y lugares</li><li><Icon name="check" />Resuelve tus dudas en español</li></ul><Link to="/asistente" className="button primary small">Hablar con el Assistant <Icon name="arrow" size={17} /></Link></article><article className="panel telegram-preview"><span className="icon-tile cyan"><Icon name="bell" size={25} /></span><h2>No te pierdas nada</h2><p>Tu aventura también vive en Telegram. Vincula tu cuenta y recibe las novedades de tus inscripciones.</p><div className="notification-example"><Icon name="shield" /><span>Tus confirmaciones y recordatorios, en un mismo lugar.</span></div><Link to="/vinculacion" className="subtle-link">Vincular Telegram <Icon name="arrow" size={17} /></Link></article></section>;
}

export default function HomePage({ catalogOnly = false }) {
  const [category, setCategory] = useState('');
  const [search, setSearch] = useState('');
  const [query, setQuery] = useState('');
  const [date, setDate] = useState('');
  const [place, setPlace] = useState('');
  const [how, setHow] = useState(false);
  const all = useQuery(signal => catalogoRequest({ action: 'LISTADO' }, { signal }).then(data => requireList(data, 'eventos')));
  const filtered = useQuery(signal => catalogoRequest({ action: 'FILTRO', categoria: category }, { signal }).then(data => requireList(data, 'eventos')), category, !!category);
  const source = category ? filtered : all;
  const events = all.data || [];
  const categories = [...new Set(events.map(event => event.categoria).filter(Boolean))];
  const places = [...new Set(events.map(event => event.lugar).filter(Boolean))];
  const dates = [...new Set(events.map(event => event.fecha).filter(Boolean))].sort();
  const visible = (source.data || []).filter(event => (!query || `${event.nombre} ${event.descripcion} ${event.lugar} ${event.categoria}`.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es'))) && (!date || event.fecha === date) && (!place || event.lugar === place));
  const explore = () => document.getElementById('catalogo')?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' });
  return <div className="home-page">{!catalogOnly && <section className="hero"><div className="hero-shade" /><div className="hero-content"><span className="eyebrow"><span className="tiny-line" />EVENTOS · COMUNIDAD · EXPERIENCIAS INCREÍBLES</span><h1>Tu pase al universo<br /><span className="gradient-text">Comic Con</span><span className="hero-period">.</span></h1><p>Anime, cosplay, gaming y un mundo por descubrir.<br className="desktop-break" /> Encuentra tu próximo evento y vívelo con tu comunidad.</p><div className="hero-actions"><button className="button primary" onClick={explore}>Explorar eventos <Icon name="arrow" /></button><button className="button glass" onClick={() => setHow(!how)} aria-expanded={how} aria-controls="how-it-works"><Icon name="play" size={16} />Cómo funciona</button></div><div className="hero-footnote"><span className="live-dot" />Tu próximo gran recuerdo empieza aquí</div></div><div className="hero-stamp" aria-hidden="true"><span>UN UNIVERSO.</span><strong>INFINITAS<br />EXPERIENCIAS.</strong><span>ESTE ES TU LUGAR ↗</span></div></section>}
    <div className="content-wrap">{how && <section id="how-it-works" className="how-it-works"><div><b>01</b><h2>Encuentra tu universo</h2><p>Explora el catálogo y descubre todos los detalles.</p></div><div><b>02</b><h2>Prepara tu pase</h2><p>Crea tu cuenta y vincula Telegram para inscribirte.</p></div><div><b>03</b><h2>Vive la experiencia</h2><p>Consulta tu inscripción y recibe tus recordatorios.</p></div></section>}{catalogOnly && <div className="page-heading"><span className="eyebrow cyan-text">ENCUENTRA TU PRÓXIMA AVENTURA</span><h1>Explora tu universo</h1><p>Todos los eventos de tu comunidad, en un solo lugar.</p></div>}
      <section id="catalogo" className="catalog-section" aria-label="Catálogo de eventos"><form className="search-bar" role="search" onSubmit={event => { event.preventDefault(); setQuery(search.trim()); }}><label className="search-input"><Icon name="search" /><span className="sr-only">Buscar eventos, lugares o temáticas</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar eventos, lugares o temáticas…" /></label><label className="search-select"><Icon name="calendar" /><span><small>Fecha</small><select aria-label="Filtrar por fecha" value={date} onChange={event => setDate(event.target.value)}><option value="">Todas las fechas</option>{dates.map(value => <option key={value} value={value}>{value.split('-').reverse().join('/')}</option>)}</select></span></label><label className="search-select location-select"><Icon name="pin" /><span><small>Ubicación</small><select aria-label="Filtrar por ubicación" value={place} onChange={event => setPlace(event.target.value)}><option value="">Todos los lugares</option>{places.map(value => <option key={value} value={value}>{value}</option>)}</select></span></label><button className="button primary" type="submit" disabled={source.loading}>Buscar eventos <Icon name="arrow" size={18} /></button></form>
      <div className="category-filters" aria-label="Filtrar por categoría"><button className={`category-filter all ${!category ? 'selected' : ''}`} onClick={() => setCategory('')} aria-pressed={!category}><Icon name="grid" size={18} />Todas</button>{categories.map(value => { const style = categoryStyle(value); return <button key={value} className={`category-filter ${style.tone} ${category === value ? 'selected' : ''}`} onClick={() => setCategory(value)} aria-pressed={category === value}><Icon name={style.icon} />{style.label}</button>; })}<span className="catalog-caption">Encuentra tu comunidad <Icon name="star" size={15} /></span></div>
      <div className="section-heading catalog-heading"><div><h2><Icon name="star" size={24} />{category ? categoryStyle(category).label : catalogOnly ? 'Todos los eventos' : 'Tu próxima gran experiencia'}</h2><p>Descubre lo que está pasando en tu universo.</p></div><span className="result-count" aria-live="polite">{!source.loading && !source.error ? `${visible.length} eventos` : ''}</span></div>
      {(query || date || place || category) && <div className="filter-summary"><span>{query ? `Resultados para “${query}”` : 'Filtros aplicados'}</span><button className="text-button" onClick={() => { setQuery(''); setSearch(''); setDate(''); setPlace(''); setCategory(''); }}>Limpiar filtros <Icon name="close" size={14} /></button></div>}
      {source.loading ? <div className="catalog-loading"><LoadingSpinner label="Buscando tu próxima aventura…" /><div className="skeleton-grid" aria-hidden="true">{[1, 2, 3, 4].map(value => <div className="skeleton-card" key={value} />)}</div></div> : source.error ? <ErrorMessage error={source.error} onRetry={source.reload} /> : visible.length ? <div className="events-grid">{visible.map(event => <EventCard key={event.evento_id} event={event} />)}</div> : <EmptyState icon="search" title="Todavía no hay eventos por aquí">Prueba otra búsqueda o vuelve pronto para descubrir nuevas experiencias.</EmptyState>}
      </section><DashboardPanels events={events} /><div className="community-strip"><Icon name="planet" size={30} /><p>No importa de qué universo vengas.<strong> Aquí encuentras a los tuyos.</strong></p><Link to="/registro" className="subtle-link">Únete a EventPass <Icon name="arrow" size={18} /></Link></div></div></div>;
}
